# Generated by Django 5.2 on 2025-06-14 19:03

import django.core.validators
import users.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=11, null=True, unique=True, validators=[users.validators.valid_cpf_validator, django.core.validators.RegexValidator(message='O CPF de conter 11 números', regex='^[0-9]{11}$'), django.core.validators.MinLengthValidator(11)], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True, validators=[users.validators.legal_age_validator], verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Número de telefone deve conter apenas números e estar no formato: 'DDD9XXXXXXXX'", regex='^[0-9]{11}$'), django.core.validators.MinLengthValidator(11)], verbose_name='phone number'),
        ),
    ]
