# Generated by Django 5.2 on 2025-06-22 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='income'),
        ),
    ]
